version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: expense_tracker_api
    command: python core/manage.py runserver 0.0.0.0:8000
    working_dir: /backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - backend/core/.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: expense_tracker_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass

  frontend:
    build:
      context: ./frontend/my-auth-app
    ports:
      - "5173:5173"
    container_name: react_frontend
    depends_on:
      - backend

volumes:
  postgres_data:
